{
 "title": "binance-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "askPrice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "old_spread_askPrice",
   "type": "stat",
   "description": "The Old Value of Ask Price Spread",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "old_spread{price_type=\"price_spread_askPrice\"} ",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "new_spread_askPrice",
   "type": "stat",
   "description": "The New Value of Ask Price Spread",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "new_spread{price_type=\"price_spread_askPrice\"} ",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "absolute_delta_askPrice",
   "type": "graph",
   "description": "absolute_delta  ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "absolute_delta{price_type=\"absolute_delta_askPrice\"} ",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  { "title": "bidPrice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "old_spread_bidPrice",
   "type": "stat",
   "description": "The Old Value of Bid Price Spread",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "old_spread{price_type=\"price_spread_bidPrice\"} ",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "new_spread_bidPrice",
   "type": "stat",
   "description": "The New Value of Bid Price Spread",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "new_spread{price_type=\"price_spread_bidPrice\"} ",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "absolute_delta_bidPrice",
   "type": "graph",
   "description": "absolute_delta  ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "absolute_delta{price_type=\"absolute_delta_bidPrice\"} ",
     "legendFormat": "{{symbol}}"
    }
   ]
  }
 ]
}